//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOB_Monitoring_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class zone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zone()
        {
            this.zone_detail = new HashSet<zone_detail>();
        }
    
        public int zid { get; set; }
        public Nullable<double> zlatitude { get; set; }
        public Nullable<double> zlongitude { get; set; }
        public string zname { get; set; }
        public Nullable<int> zflag { get; set; }
        public string employee { get; set; }
        public Nullable<int> km { get; set; }
    
        public virtual employee employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zone_detail> zone_detail { get; set; }
    }
}
